export const events = [
    {
        start: '2025-01-21 10:00',
        end: '2025-01-21 10:30',
        title: 'Anna Brown',
        content: {
            hour: '10:00',
            guests: 1,
            title: 'Meeting Room 2',
            info: 'Breuninger - Sara Lee - (JAP)',
        },
        class: 'nam',
        disabled: true,
        split: 3,
        draggable: false,
    },
    {
        start: '2025-01-24 10:30',
        end: '2025-01-24 11:00',
        title: 'Sepahane Smith',
        content: {
            hour: '10:30',
            guests: 2,
            title: 'Meeting Room 1',
            info: 'TechHub - Petr Proku - (NAM)',
        },
        class: 'nam',
        disabled: true,
        split: 2,
        draggable: false,
    },
    {
        start: '2025-01-26 08:30',
        end: '2025-01-26 09:00',
        title: 'Anna Brown',
        content: {
            hour: '08:30',
            guests: 2,
            title: 'Meeting Room 1',
            info: 'Fooadshop - Petr Proku - (JAP)',
        },
        class: 'gip',
        disabled: true,
        split: 3,
        draggable: true,
    },
    {
        start: '2025-01-26 09:30',
        end: '2025-01-26 10:00',
        title: 'Sepahane Smith',
        content: {
            hour: '09:30',
            guests: 5,
            title: 'Meeting Room 2',
            info: 'Breuninger - Sara Lee - (NAM)',
        },
        class: 'jap',
        disabled: false,
        split: 2,
        draggable: false,
    },
    {
        start: '2025-01-21 11:00',
        end: '2025-01-21 12:00',
        title: 'Martin Smith',
        content: {
            hour: '11:00',
            guests: 4,
            title: 'Meeting Room 1',
            info: 'Breuninger - Petr Proku - (GIP)',
        },
        class: 'nam',
        disabled: false,
        split: 1,
        draggable: false,
    },
    {
        start: '2025-01-22 09:30',
        end: '2025-01-22 11:00',
        title: 'Anna Brown',
        content: {
            hour: '09:30',
            guests: 1,
            title: 'Meeting Room 2',
            info: 'TechHub - Sara Lee - (NAM)',
        },
        class: 'gip',
        disabled: true,
        split: 2,
        draggable: true,
    },
    {
        start: '2025-01-24 10:30',
        end: '2025-01-24 12:00',
        title: 'Martin Smith',
        content: {
            hour: '10:30',
            guests: 1,
            title: 'Meeting Room 2',
            info: 'Breuninger - Sara Lee - (GIP)',
        },
        class: 'nam',
        disabled: true,
        split: 3,
        draggable: true,
    },
    {
        start: '2025-01-21 10:30',
        end: '2025-01-21 11:00',
        title: 'Anna Brown',
        content: {
            hour: '10:30',
            guests: 2,
            title: 'Meeting Room 3',
            info: 'Breuninger - Sara Lee - (NAM)',
        },
        class: 'gip',
        disabled: true,
        split: 2,
        draggable: false,
    },
    {
        start: '2025-01-23 14:00',
        end: '2025-01-23 15:00',
        title: 'Anna Brown',
        content: {
            hour: '14:00',
            guests: 5,
            title: 'Meeting Room 1',
            info: 'TechHub - Tim Hasselbush - (GIP)',
        },
        class: 'nam',
        disabled: false,
        split: 3,
        draggable: true,
    },
    {
        start: '2025-01-23 13:30',
        end: '2025-01-23 14:00',
        title: 'Martin Smith',
        content: {
            hour: '13:30',
            guests: 2,
            title: 'Meeting Room 1',
            info: 'Breuninger - Sara Lee - (JAP)',
        },
        class: 'nam',
        disabled: false,
        split: 3,
        draggable: false,
    },
    {
        start: '2025-01-26 17:30',
        end: '2025-01-26 18:00',
        title: 'John Smith',
        content: {
            hour: '17:30',
            guests: 4,
            title: 'Meeting Room 3',
            info: 'Breuninger - Petr Proku - (JAP)',
        },
        class: 'nam',
        disabled: true,
        split: 3,
        draggable: false,
    },
    {
        start: '2025-01-21 08:30',
        end: '2025-01-21 09:00',
        title: 'Anna Brown',
        content: {
            hour: '08:30',
            guests: 2,
            title: 'Meeting Room 2',
            info: 'Breuninger - Sara Lee - (GIP)',
        },
        class: 'nam',
        disabled: false,
        split: 2,
        draggable: true,
    },
    {
        start: '2025-01-21 11:30',
        end: '2025-01-21 12:00',
        title: 'Anna Brown',
        content: {
            hour: '11:30',
            guests: 5,
            title: 'Meeting Room 3',
            info: 'TechHub - Petr Proku - (GIP)',
        },
        class: 'gip',
        disabled: false,
        split: 3,
        draggable: true,
    },
    {
        start: '2025-01-21 16:30',
        end: '2025-01-21 17:00',
        title: 'Anna Brown',
        content: {
            hour: '16:30',
            guests: 2,
            title: 'Meeting Room 3',
            info: 'Fooadshop - Petr Proku - (NAM)',
        },
        class: 'gip',
        disabled: false,
        split: 1,
        draggable: false,
    },
    {
        start: '2025-01-22 15:30',
        end: '2025-01-22 16:30',
        title: 'Martin Smith',
        content: {
            hour: '15:30',
            guests: 4,
            title: 'Meeting Room 4',
            info: 'Breuninger - Petr Proku - (NAM)',
        },
        class: 'nam',
        disabled: true,
        split: 1,
        draggable: false,
    },
    {
        start: '2025-01-25 12:00',
        end: '2025-01-25 13:00',
        title: 'Lucas Miller',
        content: {
            hour: '12:00',
            guests: 1,
            title: 'Meeting Room 2',
            info: 'Fooadshop - Petr Proku - (NAM)',
        },
        class: 'nam',
        disabled: false,
        split: 2,
        draggable: false,
    },
    {
        start: '2025-01-24 16:30',
        end: '2025-01-24 17:30',
        title: 'John Smith',
        content: {
            hour: '16:30',
            guests: 4,
            title: 'Meeting Room 1',
            info: 'Fooadshop - Sara Lee - (JAP)',
        },
        class: 'nam',
        disabled: true,
        split: 1,
        draggable: false,
    },
    {
        start: '2025-01-22 17:00',
        end: '2025-01-22 18:30',
        title: 'John Smith',
        content: {
            hour: '17:00',
            guests: 4,
            title: 'Meeting Room 1',
            info: 'Fooadshop - Sara Lee - (NAM)',
        },
        class: 'nam',
        disabled: true,
        split: 3,
        draggable: false,
    },
    {
        start: '2025-01-22 12:00',
        end: '2025-01-22 13:00',
        title: 'Sepahane Smith',
        content: {
            hour: '12:00',
            guests: 4,
            title: 'Meeting Room 4',
            info: 'Fooadshop - Tim Hasselbush - (GIP)',
        },
        class: 'gip',
        disabled: true,
        split: 2,
        draggable: false,
    },
    {
        start: '2025-01-24 14:00',
        end: '2025-01-24 15:30',
        title: 'John Smith',
        content: {
            hour: '14:00',
            guests: 3,
            title: 'Meeting Room 2',
            info: 'TechHub - Tim Hasselbush - (GIP)',
        },
        class: 'jap',
        disabled: false,
        split: 1,
        draggable: false,
    },
    {
        start: '2025-01-24 12:00',
        end: '2025-01-24 14:00',
        title: 'LUNCH',
        content: {
            hour: '12:30',
            guests: 1,
            title: 'Meeting Room 3',
            info: 'Fooadshop Petr Proku - (NAM)'
        },
        class: 'disabled',
        disabled: true,
        background: true
    },
];
